show dbs
use store
db.products.drop()
db.products.dropIndex("*")
db.products.ensureIndex({"sku":1},{"unique":true} )
db.products.ensureIndex({"price":-1} )
db.products.ensureIndex({"description":1} )
db.products.ensureIndex({"category":1, "brand":1} )
db.products.ensureIndex({"reviews.author":1} )
print ("List of indexes");
db.products.insert({"sku": 1, "price": 1000, "description": "blablabla" })
db.products.getIndexes()
print ("Answer 1")
db.products.find({'brand':"GE"})
db.products.find({'brand':"GE"}).explain()
print ("Answer 2")
db.products.find({'brand':"GE"}).sort({price:1})
db.products.find({'brand':"GE"}).sort({price:1}).explain()
print ("Answer 3")
db.products.find({$and:[{price:{$gt:30}},{price:{$lt:50}}]}).sort({brand:1})
db.products.find({$and:[{price:{$gt:30}},{price:{$lt:50}}]}).sort({brand:1}).explain()
print ("Answer 4")
db.products.find({brand:'GE'}).sort({category:1, brand:-1}).explain()
db.products.find({brand:'GE'}).sort({category:1, brand:-1}).explain().explain()
